# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rscribd"
  s.version = "1.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tim Morgan", "Jared Friedman", "Mike Watts", "Adit Bhargava"]
  s.date = "2011-07-05"
  s.description = "The official Ruby gem for the Scribd API. Scribd is a document-sharing website allowing people to upload and view documents online."
  s.email = "api@scribd.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "History.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/rscribd.rb",
    "lib/scribd/api.rb",
    "lib/scribd/category.rb",
    "lib/scribd/collection.rb",
    "lib/scribd/document.rb",
    "lib/scribd/errors.rb",
    "lib/scribd/resource.rb",
    "lib/scribd/security.rb",
    "lib/scribd/user.rb",
    "lib/support/buffered_upload_io.rb",
    "lib/support/extensions.rb",
    "lib/support/multipart_hack.rb",
    "rscribd.gemspec",
    "sample/01_upload.rb",
    "sample/02_user.rb",
    "sample/test.txt",
    "spec/api_spec.rb",
    "spec/category_spec.rb",
    "spec/collection_spec.rb",
    "spec/document_spec.rb",
    "spec/error_spec.rb",
    "spec/resource_spec.rb",
    "spec/rscribd_spec.rb",
    "spec/security_spec.rb",
    "spec/spec_helper.rb",
    "spec/user_spec.rb"
  ]
  s.homepage = "http://www.scribd.com/developers"
  s.require_paths = ["lib"]
  s.rubyforge_project = "rscribd"
  s.rubygems_version = "1.3.7"
  s.summary = "Ruby client library for the Scribd API"

  s.add_runtime_dependency "mime-types", [">= 0"]
  s.add_runtime_dependency "addressable"
  s.add_development_dependency "rspec", [">= 0"]
  s.add_development_dependency "yard", [">= 0"]
end

